#Chama a imagem do debian como base para o build
FROM debian:9
MAINTAINER Amaury Souza [amaurybsouza@gmail.com]
RUN apt-get update -y
RUN apt-get install apache2 -y
RUN apt-get install mariadb-common mariadb-server mariadb-client -y
