# Chama a imagem "ubuntu:16.04" como imagem base para o build
# O FROM é obrigatório no início
FROM ubuntu:18.04
MAINTAINER Amaury Souza
 
# Atualizado o repo, instala o NGINX e remove o cache do APT
RUN apt-get update -y
RUN apt-get install -y nginx 

